AllCops:
  NewCops: enable
  Exclude:
    - vendor/bundle/**/*
    - bin/*
    - public/**/*

Style/Encoding:
  Enabled: false
Style/Documentation:
  Enabled: false
Metrics/MethodLength:
  Max: 15
Metrics/BlockLength:
  Max: 100
